### ISSUE TITLE
checkm_tf & checkm_pf

### ISSUE THREAD

**Issue by JaphethLin** [a-h-b/binny#22]
Hi,
I tried to run your pipe, but I couldn't find the files : checkm_tf and checkm_pf during initialization.
Could you tell me where I can download them ？

**Comment by ohickl** [comment]
Hey,
they should be loaded during the initialization step with
`./binny -i config/config.init.yaml `. Did you notice any errors while running that?

Best
Oskar

**Comment by JaphethLin** [comment]
Thank you very much for your patient reply，
I tried initialization again, but kept getting such an error. I don't know what went wrong

**Comment by ohickl** [comment]
Are there files in 
> /public4/home/sc56758/home/lim/rdrdd/tk/binny-main/database/hmms/checkm_tf/
/public4/home/sc56758/home/lim/rdrdd/tk/binny-main/database/hmms/checkm_pf/

? They should be created already before the Mantis setup runs.
Could you try deleting the binny directory, loading the latest release and install again? Might just be a recent compatibility problem with the latest Mantis and UniFunc versions we fixed.

**Comment by JaphethLin** [comment]
Oh, I discovered that my network problem was causing a piece of code in the Snakefile to execute incompletely.
But I can configure it manually.
Thank you very much 👍
