### ISSUE TITLE
Prokka's file writing problem

### ISSUE THREAD

**Issue by Andyargueasae** [a-h-b/binny#62]
Hi, 

It is so weird that this error today popped out for gene annotation. The job of annotate cannot pass, here is the log information I had. 

[2024-09-18T164353.446228.snakemake.log](https://github.com/user-attachments/files/17039670/2024-09-18T164353.446228.snakemake.log)

And I then checked the log information of annotate rule, everything looks fine, and the output is already there, with exit code as 0. 
[analysis_annotate.log](https://github.com/user-attachments/files/17039681/analysis_annotate.log)

**Comment by Andyargueasae** [comment]
A further investigation gives such error message when running prokka:

------------- EXCEPTION -------------
MSG: Could not write file '/data/chloroscan/binny_output/intermediary/prokka.faa': No such file or directory
STACK Bio::Root::IO::_initialize_io /home/student.unimelb.edu.au/yuhtong/mambaforge/envs/prokkaenv/lib/perl5/site_perl/Bio/Root/IO.pm:272
STACK Bio::SeqIO::_initialize /home/student.unimelb.edu.au/yuhtong/mambaforge/envs/prokkaenv/lib/perl5/site_perl/Bio/SeqIO.pm:508
STACK Bio::SeqIO::fasta::_initialize /home/student.unimelb.edu.au/yuhtong/mambaforge/envs/prokkaenv/lib/perl5/site_perl/Bio/SeqIO/fasta.pm:88
STACK Bio::SeqIO::new /home/student.unimelb.edu.au/yuhtong/mambaforge/envs/prokkaenv/lib/perl5/site_perl/Bio/SeqIO.pm:384
STACK Bio::SeqIO::new /home/student.unimelb.edu.au/yuhtong/mambaforge/envs/prokkaenv/lib/perl5/site_perl/Bio/SeqIO.pm:430
STACK toplevel /data/chloroscan/conda/7a9f0871ba17c37c7fea5f02871f8ff6_/lib/binny_Chloroscan/workflow/bin/prokkaP:1414
-------------------------------------

**Comment by ohickl** [comment]
Hi Andy,
did you find a solution? Maybe you ran out of space/file writing quota?

Best
Oskar

**Comment by Andyargueasae** [comment]
Yes. And after that I closed that issue.

My bad，the version of system python has conflicts with snakemake.

And now no more worries.

Andy

Oskar Hickl ***@***.***>于2024年9月20日 周五17:22写道：
